name: MS_PipeBronze_Diagonal_45_Down_4m
piecehammer: Hammer
m_name: $piece_pipe_bronze_diagonal_45_down_4m
sizeMultiplier: 1
m_description: $piece_pipe_bronze_diagonal_45_down_4m_desc
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_workbench
piecehammerCategory: Crafting
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData:
  health: 100
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Normal
    m_chop: Normal
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Normal
    m_spirit: Normal
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData:
  Width: 1
  Height: 1
  CheckWard: false
  AutoDestoryIfEmpty: false
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- FineWood:2:0:True
- BronzeNails:10:0:True
