name: treasure_stack
piecehammer: Hammer
m_name: $piece_treasure_stack
sizeMultiplier: 1
m_description: $piece_treasure_stack_desc
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Decor&Furniture
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: true
canBeRemoved: true
wearNTearData:
  health: 5
  damageModifiers:
    m_blunt: Weak
    m_slash: Weak
    m_pierce: Weak
    m_chop: Weak
    m_pickaxe: Weak
    m_fire: Resistant
    m_frost: Immune
    m_lightning: Immune
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- Coins:99:1:True
