name: OH_Undercroft_BuildSkull
piecehammer: Hammer
m_name: $piece_OH_Undercroft_BuildSkull
sizeMultiplier: 1
m_description: $piece_OH_Undercroft_BuildSkull_description
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Decor&Furniture
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort:
  comfort: 1
  comfortGroup: None
  comfortObject: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData:
  health: 1600
  damageModifiers:
    m_blunt: Weak
    m_slash: Weak
    m_pierce: Weak
    m_chop: Weak
    m_pickaxe: Weak
    m_fire: Immune
    m_frost: Immune
    m_lightning: Immune
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: true
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
craftingStationData:
  cStationCustomIcon: 
  discoveryRange: 4
  buildRange: 20
  craftRequiresRoof: false
  craftRequiresFire: false
  showBasicRecipes: false
  useDistance: 0
  useAnimation: 0
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- BoneFragments:3:1:True
