name: OdinsUndercroft
piecehammer: Hammer
m_name: $piece_OdinsUndercroft
sizeMultiplier: 1
m_description: $piece_OdinsUndercroft_description
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Misc
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: true
ground: true
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData: 
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- Stone:500:1:True
- BlueprintScroll_Smuggled:1:1:True
- CoinDvergers:50:1:True
