name: Ygg_AMagicLight
piecehammer: Hammer
m_name: $piece_amagiclight
sizeMultiplier: 1
m_description: $piece_amagiclight_desc
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Fire&Lights
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort:
  comfort: 1
  comfortGroup: None
  comfortObject: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData:
  health: 300
  damageModifiers:
    m_blunt: Weak
    m_slash: Normal
    m_pierce: Weak
    m_chop: Normal
    m_pickaxe: Weak
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: true
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- CoinDvergers:20:1:True
