name: h_drawbridge01
piecehammer: Hammer
m_name: $drawbridge01
sizeMultiplier: 1
m_description: $drawbridge01_desc
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_workbench
piecehammerCategory: Gates&Doors
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData:
  health: 1500
  damageModifiers:
    m_blunt: VeryResistant
    m_slash: VeryResistant
    m_pierce: Resistant
    m_chop: Normal
    m_pickaxe: Immune
    m_fire: Weak
    m_frost: VeryResistant
    m_lightning: VeryResistant
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- Wood:60:0:True
- Iron:10:0:True
- Chain:4:0:True
