name: Autumn_Birch_Sapling
piecehammer: Cultivator
m_name: $peAutumnBirchSaplingName
sizeMultiplier: 1
m_description: $peAutumnBirchSaplingDescription
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Misc
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: true
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: false
wearNTearData: 
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- BirchSeeds:1:1:True
