name: piece_blackmarble_bench
piecehammer: Hammer
m_name: $piece_blackmarble_bench
sizeMultiplier: 1
m_description: $piece_blackmarble_bench_desc
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_stonecutter
piecehammerCategory: Furniture
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort:
  comfort: 3
  comfortGroup: Chair
  comfortObject: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData:
  health: 200
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Weak
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- BlackMarble:6:1:True
- Copper:3:1:True
