name: OH_Carrots
piecehammer: Hammer
m_name: $OH_Carrots
sizeMultiplier: 1
m_description: $OH_Carrots_Description
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Decor&Furniture
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData:
  health: 50
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Normal
    m_chop: Normal
    m_pickaxe: Weak
    m_fire: Resistant
    m_frost: Resistant
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
contData:
  Width: 5
  Height: 2
  CheckWard: false
  AutoDestoryIfEmpty: false
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- Carrot:10:1:True
