name: AncientForge
piecehammer: Hammer
m_name: $piece_ancientforge
sizeMultiplier: 1
m_description: $piece_ancientforge_desc
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Crafting
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData:
  health: 300
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Weak
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: true
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
craftingStationData:
  cStationCustomIcon: 
  discoveryRange: 4
  buildRange: 20
  craftRequiresRoof: true
  craftRequiresFire: false
  showBasicRecipes: false
  useDistance: 1.7
  useAnimation: 2
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
build:
- BlueprintScroll:1:1:True
- AncientSouls:10:1:True
- Iron:10:1:True
- Flametal:5:1:True
