# Configure your webhook links for Discord output of detections by the Anticheat.
# This file live updates your hooks for the mod when changed. Feel free to change at any time.
# An example webhook is given below. Please replace with your own and remove the # before the text.

# You can change the Example Server text to say whatever you want. It is there just for you to name your hooks for differentiation. The 'Hook' property must remain the same, do not rename.

Yggdrasil Server:
  Hook: https://discord.com/api/webhooks/1180160229942505605/OzMLv9yb0tchb43miUSLWQzVWcURQ8BNnItL4bNObXY1WRigsJgirQr7vQjMdTsBBFl5
