name: mmo_mead_minor
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Mob_chunks:1:1:True
- mmo_orb2:1:1:True
