name: valkhelm
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- BlackMetal:30:15:True
- DvergrKeyFragment:5:0:True
- Eitr:30:10:True
- TrophySeekerQueen:1:0:True
