name: sven
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- DragonTear:5:0:True
- Silver:40:20:True
- Bronze:30:10:True
