name: heavybronzelegs
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Bronze:20:8:True
- LeatherScraps:10:0:True
- TrophyFrostTroll:1:0:True
- BoneFragments:0:3:True
