name: norahhelmalt
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- WolfHairBundle:10:0:True
- LinenThread:25:5:True
- TrophyGreydwarfShaman:5:0:True
- Iron:0:5:True
