name: norahchest
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Iron:10:5:True
- LinenThread:25:0:True
- Chain:3:5:True
