name: sven2legs
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- svenlegs:1:0:True
- BlackMetal:30:10:True
- WolfPelt:20:0:True
- SerpentScale:15:5:True
