name: ArmorWandererLegs
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_forge
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Iron:10:3:True
- LinenThread:20:10:True
