name: wschest
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- lagichest:1:0:True
- valkchest:1:0:True
- svenchest:1:0:True
- Eitr:20:10:True
- Silver:0:15:True
