name: swampchest
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Iron:25:10:True
- LeatherScraps:20:10:True
- TrophyDraugrElite:1:0:True
