name: BowHuntsman
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- FineWood:10:5:True
- Iron:20:10:True
- Feathers:10:5:True
- DeerHide:2:2:True
