name: loxhuntlegs
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Coins:950:100:True
- BlackMetal:20:10:True
- JuteRed:20:0:True
- TrophyGoblinShaman:1:0:True
