name: heavybearhelm
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- BlackMetal:30:0:True
- Flametal:8:5:True
- LoxPelt:15:0:True
- TrophySeekerBrute:2:0:True
- Silver:0:10:True
