name: bearchest2
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- bearchest:1:0:True
- BlackMarble:20:10:True
- Chain:20:5:True
