name: heavycarhelm
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Carapace:20:0:True
- Iron:25:0:True
- TrophyGjall:3:1:True
- Mandible:4:10:True
