- prefab: instanced_meadows_grass
  amount: 200
  biome: Meadows
  instanced: true
  scaleMax: 2.3
  maxTilt: 25
  minAltitude: 0.4
  maxAltitude: 1000
  terrainTilt: true
  fractalScale: 5
- prefab: instanced_shrub
  amount: 8
  biome: Meadows
  instanced: true
  scaleMax: 1.5
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 1000
  inForest: true
  forestTresholdMax: 1.15
  fractalThresholdMin: 0.5
- prefab: clutter_shrub_large
  enabled: false
  amount: 3
  biome: Meadows
  maxTilt: 30
  minAltitude: 0
  maxAltitude: 1000
  inForest: true
  forestTresholdMax: 1.15
  fractalThresholdMin: 0.5
- prefab: instanced_forest_groundcover_brown
  amount: 80
  biome: BlackForest
  instanced: true
  maxTilt: 25
  minAltitude: 0.5
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: instanced_forest_groundcover
  amount: 50
  biome: BlackForest
  instanced: true
  maxTilt: 25
  minAltitude: 0.5
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: instanced_swamp_grass
  amount: 150
  biome: Swamp
  instanced: true
  scaleMin: 0.8
  maxTilt: 25
  minAltitude: 0
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: instanced_heathgrass
  amount: 200
  biome: Plains
  instanced: true
  scaleMin: 0.7
  scaleMax: 1.5
  maxTilt: 30
  minAltitude: 0.5
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMax: 0.8
- prefab: grasscross_heath_green
  enabled: false
  amount: 150
  biome: Plains
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 1000
  terrainTilt: true
  fractalScale: 3
- prefab: instanced_meadows_grass_short
  amount: 250
  biome: Meadows
  instanced: true
  scaleMax: 2
  maxTilt: 25
  minAltitude: 0.3
  maxAltitude: 1000
  terrainTilt: true
  fractalScale: 5
  fractalThresholdMin: 1
  fractalThresholdMax: 3
- prefab: instanced_heathflowers
  amount: 100
  biome: Plains
  instanced: true
  maxTilt: 30
  minAltitude: 1
  maxAltitude: 1000
  fractalScale: 5
  fractalThresholdMax: 0.8
- prefab: instanced_small_rock1
  amount: 15
  instanced: true
  onUncleared: false
  onCleared: true
  scaleMax: 2
  maxTilt: 45
  minAltitude: 0
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMax: 0
- prefab: small_rock2
  enabled: false
  amount: 2
  onUncleared: false
  onCleared: true
  maxTilt: 45
  minAltitude: 0
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMax: 0
- prefab: instanced_swamp_ormbunke
  amount: 4
  biome: Swamp
  instanced: true
  scaleMin: 0.5
  maxTilt: 18
  minAltitude: 0
  maxAltitude: 1000
  terrainTilt: true
  fractalThresholdMin: 0.5
- prefab: instanced_ormbunke
  amount: 30
  biome: Meadows
  instanced: true
  maxTilt: 18
  minAltitude: 1
  maxAltitude: 4
  terrainTilt: true
  inForest: true
  fractalThresholdMin: 0.5
- prefab: instanced_ormbunke
  amount: 10
  biome: BlackForest
  instanced: true
  maxTilt: 18
  minAltitude: 1
  maxAltitude: 1000
  terrainTilt: true
  maxOceanDepth: 2
  fractalThresholdMin: 0.5
- prefab: instanced_vass
  amount: 30
  biome: Meadows, Swamp, Mountain, BlackForest, Plains, Ocean
  instanced: true
  scaleMax: 1.3
  maxTilt: 90
  minAltitude: -1
  maxAltitude: -0.1
  snapToWater: true
  fractalScale: 5
- prefab: instanced_waterlilies
  amount: 40
  biome: Meadows, BlackForest
  instanced: true
  scaleMin: 0.4
  scaleMax: 0.6
  maxTilt: 90
  minAltitude: -1.5
  maxAltitude: -0.2
  snapToWater: true
  randomOffset: 0.1
  maxOceanDepth: 1
  fractalScale: 2
- prefab: instanced_mistlands_grass_short
  amount: 400
  biome: Mistlands
  instanced: true
  scaleMin: 2
  scaleMax: 2
  maxTilt: 35
  minAltitude: 0.3
  maxAltitude: 1000
  minVegetation: 0.3
  maxVegetation: 1
  terrainTilt: true
  fractalThresholdMax: 0
- prefab: instanced_mistlands_grass_short
  amount: 400
  biome: Mistlands
  instanced: true
  maxTilt: 40
  minAltitude: 0.3
  maxAltitude: 1000
  minVegetation: 0.1
  maxVegetation: 0.3
  terrainTilt: true
  fractalThresholdMax: 0
- prefab: instanced_mistlands_rockplant
  amount: 40
  biome: Mistlands
  instanced: true
  scaleMax: 2
  minTilt: 15
  maxTilt: 45
  minAltitude: 0.3
  maxAltitude: 1000
  terrainTilt: true
  fractalScale: 5
