name: THSwordKrom
m_weight: 4
m_name: $item_sword_krom
m_description: $item_sword_krom_description
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: greatsword
  Attack_Random_Animation: 0
  Chain_Attacks: 3
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 20
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.3
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 2.6
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0.5
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Secondary_Attack:
  AttackType: Horizontal
  Attack_Animation: greatsword_secondary
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 40
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  DmgMultiplier: 2
  ForceMultiplier: 1
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 3
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 30
  Attack_Ray_Width: 0.5
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects: 
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Damage:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 215
  Spirit: 0
Damage_Per_Level:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 10
  Spirit: 0
Armor:
  armor: 20
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.05
  m_EitrRegen: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 52
  m_blockPowerPerLevel: 0
  m_timedBlockBonus: 2
  m_deflectionForce: 50
  m_deflectionForcePerLevel: 10
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 55
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 200
m_durabilityPerLevel: 50
m_equipDuration: 0.2
m_skillType: Swords
m_animationState: Greatsword
m_itemType: TwoHandedWeapon
m_toolTier: 0
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects:
  - vfx_HitSparks
  - sfx_sword_hit
  - fx_hit_camshake
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects: 
  Trigger_Effect:
  - fx_swing_camshake
  Trail_Effect:
  - sfx_kromsword_swing
