name: ShieldWood
m_weight: 4
m_name: $item_shield_wood
m_description: $item_shield_wood_description
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack: 
Secondary_Attack: 
Damage: 
Damage_Per_Level: 
Armor:
  armor: 100
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.05
  m_EitrRegen: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 6
  m_blockPowerPerLevel: 6
  m_timedBlockBonus: 1.5
  m_deflectionForce: 20
  m_deflectionForcePerLevel: 5
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 4
m_knockback: 40
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 200
m_durabilityPerLevel: 50
m_equipDuration: 0.2
m_skillType: Blocking
m_animationState: Shield
m_itemType: Shield
m_toolTier: 0
m_maxQuality: 3
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects:
  - vfx_clubhit
  - sfx_club_hit
  Hit_Terrain_Effects: 
  Start_Effect:
  - sfx_club_swing
  Hold_Start_Effects: 
  Trigger_Effect: 
  Trail_Effect: 
