name: AtgeirHimminAfl
m_weight: 2.5
m_name: $item_atgeir_himminafl
m_description: $item_atgeir_himminafl_description
clonePrefabName: 
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: atgeir_attack
  Attack_Random_Animation: 0
  Chain_Attacks: 3
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 20
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 3.2
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 20
  Attack_Ray_Width: 0.3
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 20
  Projectile_Accuraccy: 0
  Projectiles: 1
  AEffects:
    Hit_Effects:
    - fx_himminafl_hit
    Hit_Terrain_Effects: 
    Start_Effect: 
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Secondary_Attack:
  AttackType: Horizontal
  Attack_Animation: atgeir_secondary
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 40
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  DmgMultiplier: 1.5
  ForceMultiplier: 5
  StaggerMultiplier: 6
  RecoilMultiplier: 0
  AttackRange: 3
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 360
  Attack_Ray_Width: 0.3
  Lower_Dmg_Per_Hit: false
  Hit_Through_Walls: true
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  AEffects:
    Hit_Effects:
    - fx_himminafl_hit
    Hit_Terrain_Effects: 
    Start_Effect:
    - fx_himminafl_aoe
    Trigger_Effect: 
    Trail_Effect: 
    Burst_Effect: 
Damage:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 60
  Pickaxe: 0
  Pierce: 115
  Poison: 0
  Slash: 35
  Spirit: 0
Damage_Per_Level:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 6
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 0
  Spirit: 0
Armor:
  armor: 15
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.05
  m_EitrRegen: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 64
  m_blockPowerPerLevel: 0
  m_timedBlockBonus: 2
  m_deflectionForce: 40
  m_deflectionForcePerLevel: 5
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 40
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 175
m_durabilityPerLevel: 50
m_equipDuration: 0.2
m_skillType: Polearms
m_animationState: Atgeir
m_itemType: TwoHandedWeapon
m_toolTier: 0
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects:
  Hit_Effects:
  - vfx_arrowhit
  - sfx_spear_hit
  - fx_hit_camshake
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects: 
  Trigger_Effect:
  - fx_swing_camshake
  Trail_Effect:
  - sfx_atgeir_attack
