- key: ''
  command: ''
- key: wheel
  modifiers: rightalt,build
  command: _bind_build_scaling_mouse_wheel
- key: pageup
  modifiers: build
  command: _bind_move_up
- key: pageup
  modifiers: leftalt,build
  command: _bind_move_up_large
- key: pagedown
  modifiers: build
  command: _bind_move_down
- key: pagedown
  modifiers: leftalt,build
  command: _bind_move_down_large
- key: leftarrow
  modifiers: build
  command: _bind_move_left
- key: leftarrow
  modifiers: leftalt,build
  command: _bind_move_left_large
- key: rightarrow
  modifiers: build
  command: _bind_move_right
- key: rightarrow
  modifiers: leftalt,build
  command: _bind_move_right_large
- key: uparrow
  modifiers: build
  command: _bind_move_forward
- key: uparrow
  modifiers: leftalt,build
  command: _bind_move_forward_large
- key: downarrow
  modifiers: build
  command: _bind_move_backward
- key: downarrow
  modifiers: leftalt,build
  command: _bind_move_backward_large
- key: keypad0
  modifiers: build
  command: _bind_freeze_selection
- key: keypad5
  command: _bind_select
- key: keypad5
  modifiers: leftcontrol
  command: _bind_select_frozen
- key: keypad5
  modifiers: leftalt
  command: _bind_pick
- key: keypad5
  modifiers: leftcontrol,leftalt
  command: _bind_pick_frozen
- key: keypad7
  command: _bind_undo
- key: keypad9
  command: _bind_redo
