# Configure your per Moderator permissions in this file. Currently there is only one, but we can add more as the suggestions are made.
# Fill out more moderators just like the example given. This uses their Steam64ID as the key.

76561198151658830:
  Steam Display: true  # When set to true, moderators can see the user's steam information.

76561199195913807:
  Steam Display: true  # When set to true, moderators can see the user's steam information.

76561198087239952:
  Steam Display: true  # When set to true, moderators can see the user's steam information.

76561198818118013:
  Steam Display: true  # When set to true, moderators can see the user's steam information.

76561198260827140:
  Steam Display: true  # When set to true, moderators can see the user's steam information.