name: BoltBlackmetal
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
requireOnlyOneIngredient: false
reqs:
- BlackMetal:2:1:True
- Wood:8:1:True
- Feathers:2:1:True
