name: BoltIron
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:8:1:True
- Iron:1:1:True
- Feathers:2:1:True
