name: bearlegs2
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- bearlegs:1:0:True
- BlackMarble:20:10:True
- JuteBlue:10:5:True
