name: sven3
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- sven:1:0:True
- BlackMetal:30:10:True
- TrophyHatchling:5:1:True
- TrophySerpent:1:0:True
