name: loxhunthelm
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Coins:950:100:True
- BlackMetal:20:10:True
- TrophyLox:2:0:True
