name: svenlegs
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- LinenThread:40:5:True
- Silver:40:15:True
- Bronze:30:0:True
