name: $PlumgaPlantItShovel
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_workbench
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Wood:1:1:False
