name: trueskoghelm
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- skoghelm:1:0:True
- BlackMarble:20:15:True
- Eitr:20:10:True
- TrophySGolem:1:0:True
