name: ArrowPoison
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:8:1:True
- Obsidian:4:1:True
- Feathers:2:1:True
- Ooze:2:1:True
