name: chieflegs
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- DeerHide:20:10:True
- KnifeFlint:2:0:True
- SurtlingCore:2:0:True
- TrophySkeleton:2:0:True
- BoneFragments:0:10:True
