name: ArrowCarapace
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
requireOnlyOneIngredient: false
reqs:
- Carapace:4:1:True
- Feathers:2:1:True
- Wood:8:1:True
