name: warlordlegs
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Flametal:5:5:True
- BlackMarble:15:10:True
- Softtissue:15:0:True
- LoxPelt:15:0:True
