name: wslegs
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- lagipants:1:0:True
- valklegs:1:0:True
- svenlegs:1:0:True
- Eitr:20:0:True
- Silver:0:15:True
