name: ArrowFrost
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:8:1:True
- Obsidian:4:1:True
- Feathers:2:1:True
- FreezeGland:1:1:True
