name: ArrowSilver
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
requireOnlyOneIngredient: false
reqs:
- Wood:8:1:True
- Silver:1:1:True
- Feathers:2:1:True
