name: heavycarchest
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Carapace:20:10:True
- Iron:30:0:True
- TrophySkeleton:1:0:True
- Mandible:15:5:True
