name: heavywolfhelm
clonePrefabName: 
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Silver:30:10:True
- Flametal:8:5:True
- WolfHairBundle:15:0:True
- TrophyCultist_Hildir:1:0:True
