name: ArmorMistlandsHelmet
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_forge
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- Flametal:20:5:True
- LoxPelt:10:5:True
- LinenThread:10:3:True
